spring:
  application:
    name: sc-user
  cloud:
    config:
      discovery:
        enabled: true
        service-id: sc-config
      #uri: http://127.0.0.1:18888
  config:
    import: "optional:configserver:http://127.0.0.1:18888"
eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:18761/eureka
server:
  servlet:
    context-path: /${spring.application.name}
